### ISSUE TITLE
Practica8_Modelo en webassembly

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equipo-irving#3]
[Practica 8-Modelo en WebAssembly-Equipo Irving.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equipo-irving/files/11551103/Practica.8-Modelo.en.WebAssembly-Equipo.Irving.pdf)

**Comment by Heidi-19** [comment]
Calificación = 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
